version: '3.7'

services:
  registor:
      image: gliderlabs/registrator:latest
      volumes: 
         - "/var/run/docker.sock:/tmp/docker.sock"
      network_mode: "host"
      depends_on:
         - consul_mysql
         - consul_server
      command: --ip=10.70.176.182 consul://10.70.176.182:8500

  mysql:
      image: mysql:latest
      volumes:
        - "/Users/bytedance/mysql:/var/lib/mysql"
      environment:
         MYSQL_ROOT_PASSWORD: 123456yd
      ports:
         - "3306:3306"
  consul_mysql:
       image: consul
       depends_on:
         - mysql
       command: agent -node=mysql  -join consul_server
  consul_server:
        image: consul
        ports:
           - "8500:8500"
           - "8301:8301"
        command: agent -server -bootstrap-expect 1 -ui -node server -bind 0.0.0.0 -client 0.0.0.0


