version: '3.7'

services:
  mysql:
      image: mysql:latest
      volumes:
        - "/Users/bytedance/mysql:/var/lib/mysql"
      environment:
         MYSQL_ROOT_PASSWORD: 123456yd
         MYSQL_DATABASE: myData
      ports:
         - "3306:3306"
